name: pvpogo-tools

volumes:
  production_postgres_data: {}
  production_postgres_data_backups: {}
  production_traefik: {}
  production_django_media: {}

services:
  django:
    build:
      context: .
      dockerfile: ./Dockerfile
    image: pogo_pvp_tools_production_django
    volumes:
      - production_django_media:/app/pogo_pvp_tools/media
    env_file:
      - ./.env
    command: /start
    networks:
      - captain-overlay-network

networks:
  captain-overlay-network:
    external: true
