
volumes:
  production_postgres_data: {}
  production_postgres_data_backups: {}
  production_traefik: {}
  production_django_media: {}

services:
  django:
    build:
      context: .
      dockerfile: ./Dockerfile
      target: production
    init: true
    image: pvpogo_tools_prod_django
    volumes:
      - production_django_media:/app/pvpogo_tools/media
    depends_on:
      - postgres
    environment:
      - DEBUG=false
    env_file:
      - .env
    command: /start

  dev:
    build:
      context: .
      dockerfile: ./Dockerfile
      target: development
    init: true
    image: pvpogo_tools_dev_django
    volumes:
      - production_django_media:/app/pogo_pvp_tools/media
    depends_on:
      - postgres
    environment:
      - DEBUG=false
    env_file:
      - .env
    command: /start

  postgres:
    image: docker.io/postgres:15
    volumes:
      - production_postgres_data:/var/lib/postgresql/data
      - production_postgres_data_backups:/backups
    env_file:
      - .env
