name: pvpogo-tools

volumes:
  production_postgres_data: {}
  production_postgres_data_backups: {}
  production_traefik: {}
  production_django_media: {}

services:
  django:
    build:
      context: .
      dockerfile: ./Dockerfile
    image: gopvp_production_django
    env_file:
      - ./.env
    volumes:
      - production_django_media:/app/gopvp/media
    init: true
    command: ./start
