# Changes here will be overwritten by Copier; NEVER EDIT MANUALLY
_commit: v2024.6
_src_path: https://github.com/westerveltco/django-twc-project.git
admin_email: ""
author_name: Vu H. Chu-Le
current_version: 2024.3.1
default_from_email: ""
django_version: "5.0.3"
domain_name: gobattledex.com
extra_requirements_files:
github_owner: Vu H. Chu-Le
github_repo: gbd
include_vite: false
include_weasyprint: false
module_name: gbd
op_vault: gbd
postgres_docker_image: postgres
postgres_docker_version: "15"
project_name: gbd
python_version: "3.12"
sentry_dsn: ""
sentry_org: ""
sentry_project: gbd
