version: "3.8"
services:
  nginx-proxy:
    image: jwilder/nginx-proxy:alpine
    restart: always
    volumes:
      - django_static:/var/www/django/static  # serving django's statics
      - django_media:/var/www/django/media  # serving django's media
    ports:
      - "80:80"
      - "443:443"
    depends_on:
      - django
    networks:
      - captain-overlay-network

  django:
    <<: &django
      # Image for production:
      image: gbd-django:latest
      build:
        args:
          DJANGO_ENV: production
      restart: unless-stopped
      volumes:
        - django_media:/var/www/django/media
    networks:
      - captain-overlay-network
    expose:
      - "5000"

# This task is an example of how to extend existing ones:
#   some_worker:
#     <<: *django
#     command: python manage.py worker_process
#     deploy:
#       replicas: 2

networks:
  captain-overlay-network:
    external: true
volumes:
  django_media:
