#!/bin/bash

set -o errexit
set -o pipefail
set -o nounset

echo "Collecting staticfiles..."
python manage.py collectstatic --noinput
python manage.py compress

echo "Applying migrations..."
python manage.py migrate

echo "Starting server..."
exec /usr/local/bin/gunicorn config.asgi -k uvicorn.workers.UvicornWorker --config python:config.gunicorn
