#!/bin/bash

set -o errexit
set -o pipefail
set -o nounset

python manage.py migrate
exec uvicorn config.asgi:application --host 0.0.0.0 --port 8000 --forwarded-allow-ips='*' --reload --reload-include '*.html'
