#!/bin/bash

set -o errexit
set -o pipefail
set -o nounset

echo "Collecting staticfiles..."
python /app/manage.py collectstatic --noinput
python /app/manage.py compress

echo "Applying migrations..."
python manage.py migrate

echo "Starting server..."
exec /usr/local/bin/gunicorn config.asgi --bind 0.0.0.0:5000 --chdir=/app -k uvicorn.workers.UvicornWorker --config python:config.gunicorn
