# Generated by Django 5.0.2 on 2024-03-01 06:29

import django.db.models.deletion
import orjson
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('reversion', '0002_add_index_on_version_for_content_type_and_db'),
    ]

    operations = [
        migrations.CreateModel(
            name='Season',
            fields=[
                ('status', models.BooleanField(default=True)),
                ('from_date', models.DateTimeField(auto_now=True)),
                ('id', models.PositiveSmallIntegerField(primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Name')),
                ('start_date', models.DateField(verbose_name='Start date')),
                ('end_date', models.DateField(verbose_name='End date')),
            ],
            options={
                'verbose_name': 'Season',
            },
        ),
        migrations.CreateModel(
            name='GameMaster',
            fields=[
                ('timestamp', models.BigIntegerField(editable=False, primary_key=True, serialize=False, unique=True)),
                ('last_modified', models.BigIntegerField()),
                ('raw_content', models.JSONField(decoder=orjson.loads, encoder=orjson.dumps, verbose_name='Gamemaster file content')),
                ('revision', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='reversion.revision', verbose_name='Revision')),
            ],
            options={
                'verbose_name': 'Gamemaster',
                'get_latest_by': 'timestamp',
                'abstract': False,
            },
        ),
    ]
